### PR TITLE
Add SkippedLinesCount and ReadLinesCount

### LINKED ISSUE #11: Feature for getting count of read and skipped lines.
Introduce 2 new properties - `SkippedLines` and `ReadLines` or similarly named that gets the point across.

* `SkippedLines` - returns the number of skipped lines of the file.
* `ReadLines` - returns the number of read lines of the file.

I'll attempt to tackle this now as I'm in need of it. Let me know if this is something you'd like to see implemented in the library!

### PR DESCRIPTION
**Pull request by kikaragyozov**
* Added missing documentation.

Closes https://github.com/nreco/csv/issues/11

### CODE REVIEW

**Comment by VitaliyMF** [comment]
@kikaragyozov thank you for your contribution, if you need these 2 properties in your app I'm ok to accept this PR.
Only notice is about names: could you align the naming convention for "SkippedLinesCount" and "LinesReadCount"? I mean that "Lines" should be either in the beginning or as a 2nd word in both properties:

*  either "SkippedLinesCount" and "ReadLinesCount"
*  or "LinesSkippedCount" and "LinesReadCount"

(as for me, 1st variant is more natural to read)

**Comment by kikaragyozov** [comment]
> @kikaragyozov thank you for your contribution, if you need these 2 properties in your app I'm ok to accept this PR. Only notice is about names: could you align the naming convention for "SkippedLinesCount" and "LinesReadCount"? I mean that "Lines" should be either in the beginning or as a 2nd word in both properties:
> 
> * either "SkippedLinesCount" and "ReadLinesCount"
> * or "LinesSkippedCount" and "LinesReadCount"
> 
> (as for me, 1st variant is more natural to read)

First variant is indeed more natural for me as well. Are the names good enough? I thought about them being just `SkippedLines` and `ReadLines`.


Do you prefer the current the current more verbose naming, or the more shorter one? I'll make the changes once we get a handle on this as well, thank you for your time as well!

**Comment by VitaliyMF** [comment]
>  I thought about them being just SkippedLines and ReadLines

I think "Count" suffix is ok, since just "SkippedLines" may be a bit ambiguous - as a property with this name can be used for a list of skipped lines, for instance. 

One more formatting minor thing: if possible, please ensure that you use tabs indentation in all lines (not spaces).

**Comment by kikaragyozov** [comment]
Should I bump the version to 1.0.3 as well?

**Comment by VitaliyMF** [comment]
> Should I bump the version to 1.0.3 as well?

No, I'll do that by myself after nuget package publishing.

**Comment by kikaragyozov** [comment]
Done! Let me know if there's something else.

**Comment by VitaliyMF** [comment]
@kikaragyozov You can upgrade NReco.Csv reference to 1.0.3 to get these 2 new properties.

Thank you for your contribution!

**Pull request merged**
